version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run:
          name: Install ca-certificates for the test result storage
          command: apk --no-cache add ca-certificates git openssh-client
      - add_ssh_keys
      - run:
          name: Mirror to gitlab
          command: |
            printenv

            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git -C spmbt fetch --prune || git clone --mirror "${CIRCLE_REPOSITORY_URL}" spmbt.git

            cd spmbt.git
            git fetch --force --prune origin
            
            ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
            git push --force "git@gitlab.com:2acid/spmbt.git" ${CIRCLE_BRANCH}
            git push --tags --force "git@gitlab.com:2acid/spmbt.git"
            git remote prune "git@gitlab.com:2acid/spmbt.git"

# Also push changes when tags are added
workflows:
  version: 2
  push-to-gitlab:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/